version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./:/app
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - my-network
    depends_on:
      - app

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app
    command: gunicorn  wsgi:app --preload -b 0.0.0.0:5000
    volumes:
      - ./:/app
    networks:
      my-network:
        aliases:
          - flask-app

networks:
  my-network:
