[default]
LOG_FOLDER = "logs"
APPLICATION_NAME = "FLASK-TEMPLATE"
EXTENSIONS = [
    "flask_babel:Babel"
]

[development]
EXTENSIONS = [
    "dynaconf_merge",
    "flask_debugtoolbar:DebugToolbarExtension"
]