[default]
LOG_FOLDER = "logs"
APPLICATION_NAME = "FLASK-TEMPLATE"
EXTENSIONS = [
    "flask_template.commands:init_app",
]

[development]
EXTENSIONS = [
    "flask_debugtoolbar:DebugToolbarExtension"
]