"""add table parameters

Revision ID: fde0a5117d99
Revises: c3b50ef21e53
Create Date: 2021-04-29 03:31:55.410776

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "fde0a5117d99"
down_revision = "c3b50ef21e53"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "parameter",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_parameter")),
        sa.UniqueConstraint("name", name=op.f("uq_parameter_name")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("parameter")
    # ### end Alembic commands ###
